### ISSUE TITLE
User Doesn't Exist

### ISSUE THREAD

**Issue by WHacker1** [Yuriuseu/Distroot#1]
Hi, 
I tried the project on my termux and when all the commands were executed by bash script I faced an error at last

[•] Install packages using Trizen AUR helper...
Cloning into '/tmp/trizen'...
remote: Enumerating objects: 280, done.
remote: Counting objects: 100% (280/280), done.
remote: Compressing objects: 100% (197/197), done.
remote: Total 280 (delta 83), reused 278 (delta 83), pack-reused 0
Receiving objects: 100% (280/280), 52.87 KiB | 169.00 KiB/s, done.
Resolving deltas: 100% (83/83), done.
su: user IAmTheBest does not exist or the user entry does not contain all the required fields
su: user IAmTheBest does not exist or the user entry does not contain all the required fields
[•] Build existing custom packages with makepkg...
su: user IAmTheBest does not exist or the user entry does not contain all the required fields
su: user IAmTheBest does not exist or the user entry does not contain all the required fields
su: user IAmTheBest does not exist or the user entry does not contain all the required fields
[•] Copy overlay system files...
[•] Clean up and exit initial setup...
su: user IAmTheBest does not exist or the user entry does not contain all the required fields
su: user IAmTheBest does not exist or the user entry does not contain all the required fields
~ $ bash .bash_profile
su: user IAmTheBest does not exist or the user entry does not contain all the required fields
~ $
Please anyone help me out with this error
Thank you!

**Comment by WHacker1** [comment]
[•] Install rootfs and prepare for initial setup...
[*] Installing Arch Linux...
[*] Creating directory '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/archlinux'...
[*] Using cached rootfs tarball...
[*] Checking integrity, please wait...
[*] Extracting rootfs, please wait...
[*] Writing '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/archlinux/etc/profile.d/termux-proot.sh'...
[*] Writing resolv.conf file (NS 1.1.1.1/1.0.0.1)...
[*] Writing hosts file...
[*] Registering Android-specific UIDs and GIDs...
[*] Installation finished.

Now run 'proot-distro login archlinux' to log in.

[•] Copy existing dotfiles/overlays/packages...
[•] Set system locale and time zone...
Generating locales...
  en_US.UTF-8... done
Generation complete.
[•] Remove unecessary large packages...
error: target not found: linux-aarch64
error: target not found: linux-firmware
[•] Initialize pacman keyring...
==> Appending keys from archlinuxarm.gpg...
==> Locally signing trusted keys in keyring...
==> Importing owner trust values...
==> Updating trust database...
gpg: no need for a trustdb check
[•] Install/update core packages...
:: Synchronizing package databases...
 core                                                                             229.3 KiB  21.8 KiB/s 00:11 [#################################################################] 100%
 community                                                                          5.8 MiB  53.1 KiB/s 01:51 [#################################################################] 100%
 alarm                                                                             51.1 KiB  11.5 KiB/s 00:04 [#################################################################] 100%
 aur                                                                                8.9 KiB  3.52 KiB/s 00:03 [#################################################################] 100%
warning: base-2-2 is up to date -- reinstalling
:: There are 24 members in group base-devel:
:: Repository core
   1) autoconf  2) automake  3) binutils  4) bison  5) fakeroot  6) file  7) findutils  8) flex  9) gawk  10) gcc  11) gettext  12) grep  13) groff  14) gzip  15) libtool  16) m4
   17) make  18) pacman  19) patch  20) pkgconf  21) sed  22) sudo  23) texinfo  24) which

Enter a selection (default=all):
warning: gettext-0.21-1 is up to date -- reinstalling
warning: sed-4.8-1 is up to date -- reinstalling
warning: which-2.21-5 is up to date -- reinstalling
:: Starting full system upgrade...
:: Replace hwids with core/hwdata? [Y/n]
resolving dependencies...
looking for conflicting packages...

Packages (121) acl-2.3.1-2  argon2-20190702-4  attr-2.5.1-2  audit-3.0.7-1  bash-5.1.016-1  brotli-1.0.9-7  ca-certificates-mozilla-3.75-1  coreutils-9.0-2  cryptsetup-2.4.3-2
               curl-7.81.0-2  db-5.3.28-5  device-mapper-2.03.15-1  dhcpcd-9.4.1-1  diffutils-3.8-1  e2fsprogs-1.46.5-3  expat-2.4.6-1  filesystem-2021.12.07-1  gc-8.2.0-2
               gcc-libs-11.2.0-3  gdbm-1.23-1  glib2-2.70.4-1  glibc-2.35-2  gnupg-2.2.32-2  gnutls-3.7.3-1  gpgme-1.17.0-2  guile-2.2.7-2.1  haveged-1.9.17-1  hwdata-0.356-1
               hwids-20210613-1 [removal]  iana-etc-20220205-1  icu-70.1-1  iproute2-5.16.0-1  iputils-20211215-1  json-c-0.15-3  kmod-29-2  krb5-1.19.2-2  ldns-1.8.1-1
               libarchive-3.6.0-1  libcap-2.63-2  libcap-ng-0.8.2-7  libedit-20210910_3.1-1  libelf-0.186-5  libffi-3.4.2-4  libgcrypt-1.9.4-1  libgpg-error-1.44-1  libldap-2.6.1-1
               libmpc-1.2.1-2  libnftnl-1.2.1-1  libnghttp2-1.47.0-1  libp11-kit-0.24.1-1  libpcap-1.10.1-2  libpipeline-1.5.5-1  libseccomp-2.5.3-3  libsecret-0.20.5-1
               libssh2-1.10.0-1  libsysprof-capture-3.42.1-3  libtasn1-4.18.0-1  libxcrypt-4.4.28-2  libxml2-2.9.13-1  licenses-20220125-1  linux-api-headers-5.16.8-1
               mpfr-4.1.0.p13-2  nano-6.2-1  ncurses-6.3-2  netctl-1.27-1  nettle-3.7.3-1.1  openssl-1.1.1.m-1  p11-kit-0.24.1-1  pacman-mirrorlist-20220222-1  pam-1.5.2-1
               pambase-20211210-1  pciutils-3.7.0-2  pcre2-10.39-1  perl-5.34.0-3  perl-error-0.17029-3  perl-mailtools-2.21-5  perl-timedate-2.33-3  pinentry-1.2.0-1  popt-1.18-3
               readline-8.1.002-1  shadow-4.11.1-1  sqlite-3.38.0-1  systemd-250.3-4  systemd-libs-250.3-4  systemd-sysvcompat-250.3-4  tpm2-tss-3.2.0-1  tzdata-2021e-1
               util-linux-2.37.4-1  util-linux-libs-2.37.4-1  xz-5.2.5-2  zlib-1:1.2.11-5  zstd-1.5.2-2  autoconf-2.71-1  automake-1.16.5-1  base-2-2  binutils-2.38-3  bison-3.8.2-1
               fakeroot-1.27-1.2  file-5.41-1  findutils-4.9.0-1  flex-2.6.4-3  gawk-5.1.1-1  gcc-11.2.0-3  gettext-0.21-1  git-2.35.1-1  grep-3.7-1  groff-1.22.4-6  gzip-1.11-1
               libtool-2.4.6+59+gb55b1cc8-2  m4-1.4.19-1  make-4.3-3.1  man-db-2.10.1-1  man-pages-5.13-1  openssh-8.9p1-1  pacman-6.0.1-3.1  patch-2.7.6-8  pkgconf-1.8.0-1
               sed-4.8-1  sudo-1.9.9-2  texinfo-6.8-2  which-2.21-5

Total Download Size:   179.71 MiB
Total Installed Size:  819.30 MiB
Net Upgrade Size:      353.96 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
 iana-etc-20220205-1-any                                                          374.4 KiB  46.7 KiB/s 00:08 [#################################################################] 100%
 filesystem-2021.12.07-1-aarch64                                                   13.7 KiB  6.03 KiB/s 00:02 [#################################################################] 100%
 linux-api-headers-5.16.8-1-any                                                  1106.9 KiB  48.8 KiB/s 00:23 [#################################################################] 100%
 tzdata-2021e-1-aarch64                                                           367.4 KiB  17.1 KiB/s 00:21 [#################################################################] 100%
 glibc-2.35-2-aarch64                                                               8.9 MiB   185 KiB/s 00:49 [#################################################################] 100%
 gcc-libs-11.2.0-3-aarch64                                                         26.5 MiB   298 KiB/s 01:31 [#################################################################] 100%
 ncurses-6.3-2-aarch64                                                           1359.1 KiB   130 KiB/s 00:10 [#################################################################] 100%
 readline-8.1.002-1-aarch64                                                       302.1 KiB  60.7 KiB/s 00:05 [#################################################################] 100%
 bash-5.1.016-1-aarch64                                                          1566.1 KiB   153 KiB/s 00:10 [#################################################################] 100%
 attr-2.5.1-2-aarch64                                                              64.6 KiB  18.6 KiB/s 00:03 [#################################################################] 100%
 acl-2.3.1-2-aarch64                                                              132.1 KiB  60.3 KiB/s 00:02 [#################################################################] 100%
 pambase-20211210-1-any                                                             3.0 KiB  1248   B/s 00:02 [#################################################################] 100%
 util-linux-libs-2.37.4-1-aarch64                                                 373.8 KiB   106 KiB/s 00:04 [#################################################################] 100%
 e2fsprogs-1.46.5-3-aarch64                                                      1100.1 KiB   234 KiB/s 00:05 [#################################################################] 100%
 openssl-1.1.1.m-1-aarch64                                                          3.3 MiB   198 KiB/s 00:17 [#################################################################] 100%
 libldap-2.6.1-1-aarch64                                                          263.2 KiB  44.8 KiB/s 00:06 [#################################################################] 100%
 krb5-1.19.2-2-aarch64                                                           1219.3 KiB   262 KiB/s 00:05 [#################################################################] 100%
 libcap-ng-0.8.2-7-aarch64                                                         40.6 KiB  17.3 KiB/s 00:02 [#################################################################] 100%
 audit-3.0.7-1-aarch64                                                            358.4 KiB   149 KiB/s 00:02 [#################################################################] 100%
 libxcrypt-4.4.28-2-aarch64                                                        85.8 KiB  19.8 KiB/s 00:04 [#################################################################] 100%
 pam-1.5.2-1-aarch64                                                              553.8 KiB   163 KiB/s 00:03 [#################################################################] 100%
 libcap-2.63-2-aarch64                                                             80.0 KiB  29.2 KiB/s 00:03 [#################################################################] 100%
 coreutils-9.0-2-aarch64                                                            2.4 MiB   306 KiB/s 00:08 [#################################################################] 100%
 zlib-1:1.2.11-5-aarch64                                                           80.1 KiB  53.0 KiB/s 00:02 [#################################################################] 100%
 xz-5.2.5-2-aarch64                                                               283.8 KiB  54.3 KiB/s 00:05 [#################################################################] 100%
 file-5.41-1-aarch64                                                              336.1 KiB   133 KiB/s 00:03 [#################################################################] 100%
 findutils-4.9.0-1-aarch64                                                        430.5 KiB  88.6 KiB/s 00:05 [#################################################################] 100%
 mpfr-4.1.0.p13-2-aarch64                                                         298.5 KiB  91.3 KiB/s 00:03 [#################################################################] 100%
 gawk-5.1.1-1-aarch64                                                            1102.4 KiB   187 KiB/s 00:06 [#################################################################] 100%
 grep-3.7-1-aarch64                                                               225.8 KiB  37.2 KiB/s 00:06 [#################################################################] 100%
 sed-4.8-1-aarch64                                                                216.6 KiB  33.9 KiB/s 00:06 [#################################################################] 100%
 libffi-3.4.2-4-aarch64                                                            40.9 KiB  18.3 KiB/s 00:02 [#################################################################] 100%
 libsysprof-capture-3.42.1-3-aarch64                                               45.0 KiB  14.8 KiB/s 00:03 [#################################################################] 100%
 glib2-2.70.4-1-aarch64                                                             2.5 MiB   171 KiB/s 00:15 [#################################################################] 100%
 icu-70.1-1-aarch64                                                                 9.3 MiB   196 KiB/s 00:49 [#################################################################] 100%
 libxml2-2.9.13-1-aarch64                                                        1217.3 KiB   124 KiB/s 00:10 [#################################################################] 100%
 gettext-0.21-1-aarch64                                                          1942.0 KiB   193 KiB/s 00:10 [#################################################################] 100%
 hwdata-0.356-1-any                                                               437.5 KiB   134 KiB/s 00:03 [#################################################################] 100%
 zstd-1.5.2-2-aarch64                                                             397.7 KiB  56.6 KiB/s 00:07 [#################################################################] 100%
 kmod-29-2-aarch64                                                                101.3 KiB  27.4 KiB/s 00:04 [#################################################################] 100%
 pciutils-3.7.0-2-aarch64                                                          89.3 KiB  47.5 KiB/s 00:02 [#################################################################] 100%
 shadow-4.11.1-1-aarch64                                                         1156.5 KiB   124 KiB/s 00:09 [#################################################################] 100%
 libgpg-error-1.44-1-aarch64                                                      220.7 KiB  79.4 KiB/s 00:03 [#################################################################] 100%
 libgcrypt-1.9.4-1-aarch64                                                        470.9 KiB   139 KiB/s 00:03 [#################################################################] 100%
 libtasn1-4.18.0-1-aarch64                                                        122.6 KiB  40.3 KiB/s 00:03 [#################################################################] 100%
 libp11-kit-0.24.1-1-aarch64                                                      354.0 KiB   127 KiB/s 00:03 [#################################################################] 100%
 systemd-libs-250.3-4-aarch64                                                     517.6 KiB  91.9 KiB/s 00:06 [#################################################################] 100%
 util-linux-2.37.4-1-aarch64                                                        2.3 MiB   274 KiB/s 00:09 [#################################################################] 100%
 pcre2-10.39-1-aarch64                                                            998.1 KiB   195 KiB/s 00:05 [#################################################################] 100%
 gzip-1.11-1-aarch64                                                               78.2 KiB  34.5 KiB/s 00:02 [#################################################################] 100%
 licenses-20220125-1-any                                                           66.7 KiB  17.2 KiB/s 00:04 [#################################################################] 100%
 expat-2.4.6-1-aarch64                                                            102.2 KiB  50.8 KiB/s 00:02 [#################################################################] 100%
 libarchive-3.6.0-1-aarch64                                                       471.3 KiB   170 KiB/s 00:03 [#################################################################] 100%
 brotli-1.0.9-7-aarch64                                                           327.0 KiB  70.0 KiB/s 00:05 [#################################################################] 100%
 libnghttp2-1.47.0-1-aarch64                                                       88.0 KiB  52.4 KiB/s 00:02 [#################################################################] 100%
 libssh2-1.10.0-1-aarch64                                                         204.6 KiB  48.0 KiB/s 00:04 [#################################################################] 100%
 p11-kit-0.24.1-1-aarch64                                                         142.1 KiB  82.1 KiB/s 00:02 [#################################################################] 100%
 ca-certificates-mozilla-3.75-1-aarch64                                           334.0 KiB  76.8 KiB/s 00:04 [#################################################################] 100%
 curl-7.81.0-2-aarch64                                                           1083.1 KiB   256 KiB/s 00:04 [#################################################################] 100%
 json-c-0.15-3-aarch64                                                             50.9 KiB  16.2 KiB/s 00:03 [#################################################################] 100%
 tpm2-tss-3.2.0-1-aarch64                                                         722.4 KiB   162 KiB/s 00:04 [#################################################################] 100%
 libsecret-0.20.5-1-aarch64                                                       172.0 KiB  62.3 KiB/s 00:03 [#################################################################] 100%
 pinentry-1.2.0-1-aarch64                                                         111.5 KiB  77.4 KiB/s 00:01 [#################################################################] 100%
 nettle-3.7.3-1.1-aarch64                                                         422.0 KiB  67.5 KiB/s 00:06 [#################################################################] 100%
 gnutls-3.7.3-1-aarch64                                                             2.6 MiB  20.0 KiB/s 02:15 [#################################################################] 100%
 sqlite-3.38.0-1-aarch64                                                         1600.6 KiB  5.71 KiB/s 04:40 [#################################################################] 100%
 gnupg-2.2.32-2-aarch64.pkg.tar.xz failed to download
 Total ( 67/120)                                                                  179.7 MiB   176 KiB/s 17:28 [#################################################################] 100%
error: failed retrieving file 'gnupg-2.2.32-2-aarch64.pkg.tar.xz' from mirror.archlinuxarm.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.
[•] Create new user and set sudo access...
useradd: invalid user name 'IAmTheBest'
-bash: /etc/sudoers.d/custom: No such file or directory
[•] Installing fakeroot with tcp/ipc support...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  531k  100  531k    0     0   3231      0  0:02:48  0:02:48 --:--:--  4975
./bootstrap: line 19: autoreconf: command not found
[•] Install packages using Trizen AUR helper...
-bash: git: command not found
-bash: cd: /tmp/trizen: No such file or directory
su: user IAmTheBest does not exist or the user entry does not contain all the required fields
[•] Build existing custom packages with makepkg...
su: user IAmTheBest does not exist or the user entry does not contain all the required fields
su: user IAmTheBest does not exist or the user entry does not contain all the required fields
su: user IAmTheBest does not exist or the user entry does not contain all the required fields
[•] Copy overlay system files...
[•] Clean up and exit initial setup...
su: user IAmTheBest does not exist or the user entry does not contain all the required fields
su: user IAmTheBest does not exist or the user entry does not contain all the required fields
~ $

**Comment by WHacker1** [comment]
Still same

**Comment by Yuriuseu** [comment]
Along these lines it says that username `IAmTheBest` is invalid:

```
[•] Create new user and set sudo access...
useradd: invalid user name 'IAmTheBest'
-bash: /etc/sudoers.d/custom: No such file or directory
[•] Installing fakeroot with tcp/ipc support...
```

Linux usernames requires all lower case. You should change it to `iamthebest` to fix this.

**Comment by WHacker1** [comment]
Bro still same error

**Comment by WHacker1** [comment]
┌── iamthebest@localhost ~
└─• exec xlaunch dbus-launch --exit-with-session startxfce4
/home/iamthebest/.local/bin/xlaunch: line 5: x11vnc: command not found
/home/iamthebest/.local/bin/xlaunch: line 4: Xvfb: command not found
/home/iamthebest/.local/bin/xlaunch: line 6: novnc: command not found
Couldn't exec startxfce4: No such file or directory
~ $

When I paste the command it says this and automatically exit the environment

**Comment by Yuriuseu** [comment]
> ┌── iamthebest@localhost ~
> └─• exec xlaunch dbus-launch --exit-with-session startxfce4
> /home/iamthebest/.local/bin/xlaunch: line 5: x11vnc: command not found
> /home/iamthebest/.local/bin/xlaunch: line 4: Xvfb: command not found
> /home/iamthebest/.local/bin/xlaunch: line 6: novnc: command not found
> Couldn't exec startxfce4: No such file or directory
> ~ $

The [`xlaunch`](https://github.com/Yuriuseu/Distroot/blob/main/dotfiles/.local/bin/xlaunch) script requires [`x11vnc`](https://archlinux.org/packages/?sort=&q=x11vnc), [`xorg-server-xvfb`](https://archlinux.org/packages/?sort=&q=xorg-server-xvfb), [`novnc`](https://aur.archlinux.org/packages?K=novnc), and [`websockify`](https://aur.archlinux.org/packages?K=websockify) packages. If you want to use XFCE for GUI, install the [`xfce4`](https://archlinux.org/groups/x86_64/xfce4/) package group or add the package name along the [`PACKAGES`](https://github.com/Yuriuseu/Distroot/blob/92b5baa06172adf47f2048ae8b1cc0e7b8ab865f/.bash_profile#L7) variable.
